### ISSUE TITLE
How to install locally and setup developer environment

### ISSUE THREAD

**Issue by huasheng-yue** [spacether/keyboardlayout#4]
ModuleNotFoundError: No module named 'keyboardlayout.common'; 'keyboardlayout' is not a package

**Comment by spacether** [comment]
Can you let me know the steps to reproduce this error? Tests are passing and pip install and usage works on my mac system.

**Comment by huasheng-yue** [comment]
I'm do test with windows10 system + anaconda3 + pycharm2020.1......


> Can you let me know the steps to reproduce this error? Tests are passing and pip install and usage works on my mac system.

**Comment by spacether** [comment]
Are you in a virtual environment with the package installed in it? 
If you have not installed the library in your python environment either global or virtual, then you will get the error that you mentioned. This is a standard part of python development and is not a bug.

Before running make test, you need to install the package into your system python or a python virtual environment.
On windows in the root of this repo that is:
```
# make a virtual env
python3 -m venv venv
# activate it
venv\Scripts\activate.bat
# install the library into your environment in developer mode
# this means that if you edit it, your edits will be used in your environment
pip3 install -e .[dev]
# run the tests
python3 setup.py pytest
```

**Comment by Hanyman8** [comment]
Hello, which Python version are you using? I ran into this problem:
`ERROR: Package 'keyboardlayout' requires a different Python: 3.6.13 not in '>=3.7'`

**Comment by spacether** [comment]
This library requires python >= 3.7 as that error message mentions.
Can you upgrade the version of python3 on your computer?
For reference I am using python 3.8.6 but any version >= 3.7 will work.

**Comment by huasheng-yue** [comment]
Thank you for your reply.

I’m using windows10+Anaconda3(with python 3.7.9)+pycharm2020.1

And I’m using the ansi 104 keyboard

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Justin Black<mailto:notifications@github.com>
发送时间: 2021年3月2日 5:08
收件人: spacether/keyboardlayout<mailto:keyboardlayout@noreply.github.com>
抄送: huasheng-yue<mailto:huashengle@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [spacether/keyboardlayout] some bugs? (#4)


This library requires python >= 3.7 as that error message mentions.
Can you upgrade the version of python3 on your computer?
For reference I am using python 3.8.6 but any version >= 3.7 will work.

―

**Comment by spacether** [comment]
How do you get into your anaconda python? I do not use anaconda. Your error message is indicating that your system python is 3.6.13 not the anaconda python version.
If you enter your anaconda python and install per my instructions above, are you able to run the tests?

**Comment by Hanyman8** [comment]
@spacether sorry, I was replying to @huasheng-yue, the python 3.6.13 was in my virtualenv, not his.

**Comment by spacether** [comment]
@huasheng-yue did you get it working? If not we can do a meeting and I can get you up and running.
Translation:
你工作了吗？如果没有，我们可以举行会议，我可以帮助您启动并运行。

**Comment by huasheng-yue** [comment]
Thank you for your reply, it's too difficlt for me, and now I used another obj... without some unknown bugs.
